# These are supported funding model platforms

github: [toxi22]
patreon: ZaboronaHelp
ko_fi: zaboronahelp
custom: ['www.privat24.ua/send/gp5xd','send.monobank.ua/jar/3FJXKRiFni','donatello.to/ZaboronaHelp']
