(/duckdns/) {next}
(/linode\.com/) {next}
(/upcloud\.com/) {next}
(/googleusercontent\.com/) {next}
(/\.sl\.pt/) {next}
(/\.biz\.ski/) {next}
(/\.sloat\.biz/) {next}
(/\.new-rutor\.org/) {next}
(/\.traderc\.biz/) {next}
(/\.o-q\.biz/) {next}
(/\.dcge\.biz/) {next}
(/fonbet/) {next}
(/betcity/) {next}
(/zerkalo/) {next}
(/zigzag/) {next}
(/zenitbet/) {next}
(/winline/) {next}
(/ttrcasino/) {next}
(/paripartners/) {next}
(/parimatch/) {next}
(/ligastavok/) {next}
(/liga-stavok/) {next}
(/baltplay/) {next}
(/azino777/) {next}
(/vulkan/) {next}
(/leonbet/) {next}
(/ru\.leon/) {next}
(/ru\.adleon/) {next}
(/leonaccess/) {next}
(/leon-[0-9]{3}/) {next}
(/pm-[0-9]{2,3}\./) {next}
(/mf-[0-9]{2,3}\.online/) {next}
(/fon-[0-9]{2,3}\./) {next}
(/most.{3}\./) {next}
(/casino\-/) {next}
(/bcity\-/) {next}
(/1x\-/) {next}
#(/1xbet/) {next}
(/1xmob/) {next}
#(/melbet/) {next}
(/bk\-info/) {next}
(/bkinfo/) {next}
(/marathon/) {next}
(/gaminator/) {next}
(/joycasino/) {next}
(/goldenstar/) {next}
/marafon/ {next}
/olimp/ {next}
/kasino/ {next}
/depozit/ {next}
/kazino/ {next}
/777/ {next}
/casino/ {next}
/admiral/ {next}
/zerkala/ {next}
/avtomat/ {next}
/igrat/ {next}
/azart/ {next}
#/besplatno/ {next}
/sloty/ {next}
/bet-boom/ {next}
/betsbc/ {next}
/^bk-/ {next}
/^bkr/ {next}
/bkinf0/ {next}
/bukmeker/ {next}
/ruletka/ {next}
/vulcan/ {next}
/vylkan/ {next}
/wulcan/ {next}
/wulkan/ {next}
/vullkan/ {next}
/volcan/ {next}
/^vlc/ {next}
/^vlk/ {next}
/eldorado/ {next}
/lotto/ {next}
/lottery/ {next}
/fbmetrix/ {next}
/^diplom-/ {next}
/^dosug-/ {next}
/^dosug[0-9]{2}/ {next}
/fon-bet/ {next}
/^hydra[0-9]{2}/ {next}
/^intim[0-9]{2}/ {next}
/^livetv[0-9]{2}/ {next}
/marafon/ {next}
#/^melb/ {next}
/^melm/ {next}
/^mf-[0-9]{2}/ {next}
/^most/ {next}
#/^new-/ {next}
/^pari-/ {next}
/^pokerdom/ {next}
/prostitutki/ {next}
/spravka/ {next}
/mossst/ {next}
/mostbet/ {next}
/diplom/ {next}
/pharaon/ {next}
/fortuna/ {next}
/^rotate/ {next}
/^ref.{5}\./ {next}
/play\-/ {next}
/^1w.{3,4}\./ {next}
/^mylove[0-9]{2,3}\./ {next}
#/^1x.{3,4}\./ {next}
/^mirror[0-9]{2,3}\./ {next}
/^mob.{3,4}\./ {next}
/^777/ {next}
/hydra/ {next}
/spravok/ {next}
/spravka/ {next}
/zenit/ {next}
/zakladki/ {next}
/vullcan/ {next}
/vulslots/ {next}
/vulwinners/ {next}
/slots/ {next}
/traffaccess/ {next}
/tide24/ {next}
/swleon/ {next}
/sportingbull/ {next}
/sokol-24/ {next}
/silmag/ {next}
/faraon/ {next}
/marbet/ {next}
/joycazino/ {next}
/joy-cazino/ {next}
/jackpot/ {next}
/semyanich/ {next}
/semenarnia/ {next}
/prostitutki/ {next}
/shishkin-semena/ {next}
/vulkanstavka/ {next}
/bukvaved/ {next}
/rastarasha/ {next}
/errors-seeds/ {next}
/casino-x/ {next}
/kinogb/ {next}
/vulkanstars/ {next}
/vulcanwin/ {next}
/vlk-slots/ {next}
/rutorg/ {next}
/leonbets/ {next}
/parimatch/ {next}
/azartplay/ {next}
/bbplay2017/ {next}
/baltplay2017/ {next}
/hiwager/ {next}
/seedbanda/ {next}
#/gidonline/ {next}
/^alco/ {next}
(/\.r\.cloudfront\.net/) {next}
(/\*/) {next}
(/\\/) {next} 
